version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile-app
    ports:
      - "8080:8080"
    links: 
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/intelygenz

  mongo:
    build:
      context: ./
      dockerfile: Dockerfile-mongo
    ports:
      - "27017"